Social Media Policy & Strategies Draft
drupaldiversity/administration pull request #100
Opened 2017-06-03 13:39 UTC by sugaroverflow

Issue #81 Social Media Strategies and Best Practices. 

After some collaboration, I put together the thoughts we've shared for our social media policies/strategies. This is a first draft and in progress. 

**Please share your thoughts via comments, committed changes, or reviews. ** 

Here are some questions I had while putting this together: 
- Responding to harassment to the group vs to it’s volunteers?
- Personal accountability - is everyone on board with the idea of one unified message? 
	- How do we feel about volunteers who have online opinions? and should we clearly state our individuals opinions are not a reflection of our mission as a group?

2017-06-07 15:10 UTC, AlannaBurke commented on content-team/working-docs/social-media-policy.md
> +*Do we disclose who is tweeting? Is that important if there's a unified message?*
So that's a no, we don't want to disclose who is tweeting? We may want to bold the `not` in the below statement.

2017-06-07 15:10 UTC, AlannaBurke commented on content-team/working-docs/social-media-policy.md
> +- Transparency, public participation and collaboration
Add period to the end of sentence for continuity :)

2017-06-07 15:11 UTC, AlannaBurke commented on content-team/working-docs/social-media-policy.md
> +How do we define harassment to the group (or it’s volunteers)?
Should be `its`

2017-06-07 15:11 UTC, AlannaBurke commented on content-team/working-docs/social-media-policy.md
> +- Moderation and participation guidelines
Add period to the end of each line for continuity :)

2017-06-07 15:13 UTC, AlannaBurke commented
This looks excellent overall, I added some nitpicky grammar and punctuation comments. There is definitely overlap here with the moderation team, so I think it's fine to say that we refer to the moderation and participation guidelines here. We are also mulling over an internal reporting strategy as well.

2017-06-07 19:59 UTC, seantwalsh3 commented on content-team/working-docs/social-media-policy.md
> +## Channels
It might be a good idea to have each of these as links to the respective channel.

2017-06-07 23:13 UTC, sugaroverflow commented
@AlannaBurke @seantwalsh3 side question, should I remove the _italic explanations_ of each section? :)

2017-06-07 23:13 UTC, sugaroverflow commented on content-team/working-docs/social-media-policy.md
> +## Channels
Yes, good point! I think that may have been lost in markdown translation.

2017-06-07 23:25 UTC, sugaroverflow commented on content-team/working-docs/social-media-policy.md
> +*Do we disclose who is tweeting? Is that important if there's a unified message?*
@AlannaBurke Hard to say for sure. I'll confirm with the leadership team and team leads. So far, no one has objected to it :) but hopefully putting the draft up during the meeting will help with that.

2017-06-08 09:33 UTC, catch56 commented on content-team/working-docs/social-media-policy.md
> +We want to post content that is related to diversity (age/race/gender/religion/more) and/or tech and various places where these issues cross over. Sharing content with different perspectives and diff
nit: should be different voices.

2017-06-08 09:36 UTC, catch56 commented on content-team/working-docs/social-media-policy.md
> +  - “We’re sorry you feel that way, can we better explain?”
'sorry you feel that way' is often used as a non-apology and I generally try to avoid it.

2017-06-08 09:38 UTC, catch56 commented on content-team/working-docs/social-media-policy.md
> +*Do we disclose who is tweeting? Is that important if there's a unified message?*
Don't think it needs signing, it should be obvious it's a collective account.

Sometimes people 'take over' accounts for a day/hour/week and introduce themselves at the start, that's interesting but doesn't really apply for general tweets.

2017-06-08 14:25 UTC, AlannaBurke commented on content-team/working-docs/social-media-policy.md
> +  - “We’re sorry you feel that way, can we better explain?”
Good call - we should come up with some better examples, these were just my off-the-cuff suggestions in the working doc.

2017-06-08 15:27 UTC, seantwalsh3 commented
@sugaroverflow I don't think you need the italic questions but I do feel that the structure of the bullets should be the same. For example under Purpose the last bullet could be "To foster transparency, public participation, and collaboration."

2017-06-27 14:36 UTC, rubyji commented on content-team/working-docs/social-media-policy.md
> +  - “We’re sorry you feel that way, can we better explain?”
Also, as a woman I make a point not to apologize for things that are not actually my fault. I do think it's good to offer more information or discussion, but we need to not assume that every disagreement is a problem that we necessarily can or should solve.

2017-06-27 14:38 UTC, rubyji commented on content-team/working-docs/social-media-policy.md
> +We want to post content that is related to diversity (age/race/gender/religion/more) and/or tech and various places where these issues cross over. Sharing content with different perspectives and diff
I suggest changing diversity to *diversity and inclusion*.

I agree with including D&I *and/or* tech, as well items that touch both areas.

2017-06-27 14:39 UTC, rubyji commented on content-team/working-docs/social-media-policy.md
> +*Do we disclose who is tweeting? Is that important if there's a unified message?*
I know I'm one of the personalities in question and I'm fine either way. I think it's been working OK without signing them, but I'm open to whatever the group wants.

2017-06-27 14:41 UTC, rubyji commented on content-team/working-docs/social-media-policy.md
> +- Be careful of what we like or retweet.  Like things judiciously and that apply directly to our mission. Do not “like” anything we would not tweet from the account.
Can we say **intentional** instead of _careful_?

2017-07-16 16:37 UTC, sugaroverflow commented
Thanks everyone for the feedback! I made all the changes suggested and I think this first draft is ready :) I'll assign a reviewer for the merge.

2017-07-16 16:39 UTC, sugaroverflow commented
Could someone approve the review on this MR? Thank you! @catch56 @AlannaBurke

2017-07-17 15:36 UTC, AlannaBurke requested changes

2017-07-17 15:36 UTC, AlannaBurke commented on content-team/working-docs/social-media-policy.md
> +- To foster transparency, public participation, and collaboration."
Remove quote here

2017-07-17 15:36 UTC, AlannaBurke commented on content-team/working-docs/social-media-policy.md
> +- For mentors, and teachers in teh Drupal community.
teh -> the

2017-07-17 15:36 UTC, AlannaBurke commented on content-team/working-docs/social-media-policy.md
> +I also think we should look through the list of articles we’ve been compiling to read and see what should be shared, and make sure we are sharing factual resources as well - various information on di
Maybe clean this up? i think this was my bullet point. How about:

We want to share the content that we are consuming, as well - links that we have compiled, links that are shared in the group, books that we read or recommend, and articles that we read. We also want to share information on basic Diversity 101, links to related sessions and presentations, as well as other factual resources.

2017-07-17 15:36 UTC, AlannaBurke commented on content-team/working-docs/social-media-policy.md
> +- Report the harassment to Twitter
Add period.

2017-07-17 17:22 UTC, sugaroverflow commented
changes made, thank you for reviewing @AlannaBurke

2017-08-08 17:54 UTC, sugaroverflow commented
@drnikki changes made on this one too

2017-08-15 20:31 UTC, merged