Slack Channel Introduction / Description
drupaldiversity/administration pull request #64
Opened 2017-05-02 20:30 UTC by sugaroverflow

We thought it would be a good idea to have an introduction for people new to our slack channel. 
This is a first pass at that, feedback welcome! :)

(I added this to the working docs/ but let me know if there's a better place - thanks!)

2017-05-03 01:27 UTC, Cottser commented
I really want to watch this now but here's the link for the New Orleans presentation :) https://events.drupal.org/neworleans2016/sessions/together-we-can-make-drupal-example-diversity-tech

2017-05-03 01:33 UTC, sugaroverflow commented
Added, thank you @Cottser !

I've watched it a few times. It makes me feel less like a DD&I imposter.

2017-05-04 16:22 UTC, cleverington commented on working-docs/slack-channel-introduction.md
> +This group was created after DrupalCon New Orleans. Nikki Stevens & Karyn Cassio gave a presentation about diversity and inclusion. ++(link presentation page)++
> _++(link presentation page)++

https://events.drupal.org/neworleans2016/sessions/together-we-can-make-drupal-example-diversity-tech

2017-05-04 16:36 UTC, justAChris commented
As a Noob to DD&I, I think this covers everything important. I'd consider promoting "We would like to:" as a header in kind of "What we do" so when people ask what the group does, it's easy to point to.

2017-05-04 16:52 UTC, sparklingrobots commented
In the channel @zombree suggested a "Getting started with Github", which I think would be an excellent addition to this doc.  I suspect there is already such a document on the internet...

...okay, after a brief search, most of it seems to be "get started with your own repo".  But I found this video for how to use github issues: https://www.youtube.com/watch?v=TJlYiMp8FuY  But it's a start, until we have something more custom for our purposes?

2017-05-04 17:16 UTC, sugaroverflow commented on working-docs/slack-channel-introduction.md
> +This group was created after DrupalCon New Orleans. Nikki Stevens & Karyn Cassio gave a presentation about diversity and inclusion. ++(link presentation page)++
Thanks! I pushed commit 575bcbf, why didn't the PR update?

2017-05-04 17:17 UTC, sugaroverflow commented on working-docs/slack-channel-introduction.md
> +This group was created after DrupalCon New Orleans. Nikki Stevens & Karyn Cassio gave a presentation about diversity and inclusion. ++(link presentation page)++
Hmm maybe this is a conversation on the older commit version. The link is there now thank you!

2017-05-05 00:23 UTC, cleverington commented
I wonder if it would be better to add this as a new page on the site?

Maybe under a link "Slackin' It" or "Slack" or something?

2017-05-05 01:53 UTC, sugaroverflow commented
@cleverington that makes sense! 

I'm thinking if we put it in the working docs for now, I can add this info to the Getting Involved page on the website under a 'Slack Channel' heading?

2017-05-05 01:56 UTC, sugaroverflow commented
@justAChris Thank you for the feedback, it's super appreciated! I'm a little confused, where were you proposing it would be better to use "What we would like to do" as a heading? I like the idea, I'm just not sure where it would go. Instead of "Who We Are"?

2017-05-05 15:01 UTC, justAChris commented
@sugaroverflow I misread it a bit. On initial read I thought that the “We would like to:” bullet points spoke more to that goals of the group instead of the purpose of the channel. Since this document is specifically talking about the slack channel, those ideas fit fine under “What this channel is for”, so the headings are great as is.

I would suggest we replace the “We would like to:” text since that comes off soft to me. Something like "In this channel we:” or “The purpose of this channel is to:"

2017-05-05 15:25 UTC, justAChris requested changes

2017-05-05 15:25 UTC, justAChris commented on working-docs/slack-channel-introduction.md
> +We are not affiliated with the DA and our booth/stickers are all funded by donations.
> DA

Drupal Association

2017-05-05 15:25 UTC, justAChris commented on working-docs/slack-channel-introduction.md
> +- provide a safe (but moderated?) space to discuss issues of diversity and inclusion within the Drupal community.
> provide a safe (but moderated?) space

provide a moderated, safe space

2017-05-05 17:20 UTC, johnshortess commented on working-docs/slack-channel-introduction.md
> +- advocate for a more open and diverse community whether through these conversations, presentations at camps and conferences, and BOF sessions.
- Advocate for a more open and diverse Drupal community through Slack/IRC conversations, presentations and camps and conferences, BOF sessions, and other means

I started out by eliminating "whether" (which is superfluous), and got carried away. :)

Also, for consistency, all bullet items should start with a capital letter, and all should ether have or not have a period (or other appropriate punctuation) at the end.

2017-05-05 17:20 UTC, johnshortess commented on working-docs/slack-channel-introduction.md
> +We would hope to inspiring others to help tell their stories and bring people together to make our community a place where more people can feel welcome.
We hope to inspire others to help tell their stories and bring people together to make our community a place where more people can feel welcome.

2017-05-05 23:37 UTC, cleverington commented
Added all recommendations.

2017-05-08 14:30 UTC, sugaroverflow commented
Thanks @cleverington! I think this is ready for review :)

2017-05-09 16:51 UTC, justAChris approved these changes
Nothing further from me.

2017-05-11 16:37 UTC, merged

2017-05-11 16:57 UTC, sugaroverflow commented
Note for self: need to add the participation and moderation guidelines as an update to this.